export default [
  "#core",
  "https://github.com/pex-gl/pex-context",
  "https://github.com/pex-gl/pex-renderer",
  "https://github.com/pex-gl/pex-gl",
  "https://github.com/pex-gl/pex-math",
  "https://github.com/pex-gl/pex-color",
  "https://github.com/pex-gl/pex-random",
  "https://github.com/pex-gl/pex-io",
  "https://github.com/pex-gl/pex-cam",
  "https://github.com/pex-gl/pex-gui",
  "https://github.com/pex-gl/pex-geom",

  "#geom/primitives",
  "primitive-geometry",
  "primitive-box",
  "primitive-capsule",
  "primitive-circle",
  "primitive-cylinder",
  "primitive-cube",
  "primitive-icosphere",
  "primitive-plane",
  "primitive-quad",
  "primitive-rounded-cube",
  "primitive-sphere",
  "primitive-torus",
  "primitive-ellipsoid",
  "primitive-octasphere",
  "geo-arc",

  "#geom/3d",
  "geom-builder",
  "geom-center-and-normalize",
  "geom-edges",
  "geom-half-edge",
  "geom-merge",
  "geom-normals",
  "geom-split-vertices",
  "geom-revolve",
  "geom-sweep",
  "geom-triangulate",
  "spline-points",
  "latlon-to-xyz",
  "xyz-to-latlon",
  "ray-geom-intersections",
  "frenet-serret-frames",
  "path-tangents",
  "vector-field",

  "#geom/2d",
  "hammersley",
  "fit-rect",
  "perspective-grid",
  "grid-cells",

  "#algo/3d",
  "space-colonization",
  "spatial-index",

  "#canvas",
  "canvas-context",
  "canvas-pattern",
  "canvas-record",
  "canvas-screenshot",
  "canvas-thumbnail-cache",
  "canvas-tint-image",

  "#math",
  "interpolate-angle",
  "interpolate-arrays",
  "concat-typed-array",
  "interleave-typed-array",
  "eases",
  "lerp",
  "eerp",

  "#color",
  "cosine-gradient",

  "#io",
  "parse-dds",
  "parse-hdr",
  "geom-parse-obj",
  "geom-export-obj",

  "#glsl",
  "glsl-conditionals",
  "glsl-constants",
  "glsl-rotate",
  "glsl-smaa",
  "glsl-tone-map",

  "#sys",
  "raf-perf",
  "is-browser",
  "is-plask",
  "is-electron-renderer",
  "is-mobile",

  "#tutorials",
  "https://github.com/pex-gl/pex-examples",
  "https://github.com/vorg/pragmatic-pbr",
  // "https://github.com/vorg/pex-experiments",
];
